export const ROUTES = {
  ROLE_SELECT: 'RoleSelect',
  FAMILY_LOGIN: 'FamilyLogin',
  FAMILY_REGISTER: 'FamilyRegister',
  CHILD_LOGIN: 'ChildLogin',
  CHILD_PERMISSION: 'ChildPermission',
  FAMILY_TABS: 'FamilyTabs',
  CHILD_TABS: 'ChildTabs',
  FAMILY_DASHBOARD: 'FamilyDashboard',
  GEOFENCE_MAP: 'GeofenceMap',
  ROUTINE_MANAGER: 'RoutineManager',
  ADD_ROUTINE: 'AddRoutine',
  ALERT_HISTORY: 'AlertHistory',
  SAFE_POINTS: 'SafePoints',
  CHILD_DASHBOARD: 'ChildDashboard',
  ROUTINE_TRACK: 'RoutineTrack',
  REWARDS: 'Rewards',
  SAFE_NAVIGATION: 'SafeNavigation',
  GAME_ZONE: 'GameZone',
};
